language: nix
sudo: false
env:
    - NIX_PATH=nixpkgs=https://d3g5gsiof5omrk.cloudfront.net/nixos/17.09/nixos-17.09.3159.c665fcca9e7/nixexprs.tar.xz
script:
- nix-shell -p haskellPackages.hlint --run "hlint ."
- nix-shell -p stack --run "stack build --nix"
cache:
    directories:
        - $HOME/.stack
